app:
  version: "v0.0.1"
  name: "qishuBooks"
  mode: "dev"

log:
  level: ""
  filename: ""
  max_size: 50
  max_age: 7
  max_backups: 3

mysql:
  host: 10.0.0.200
  port: 13306
  user: "root"
  password: "Abc12345.hello"
  dbname: "qishubook"
  max_open_cons: 200
  max_idle_cons: 10

redis:
  host: ""
  port:
  password: ""
  db:
  pool_size:
